### ISSUE TITLE
error after clicking on "Restore Foreign Keys" button

### ISSUE THREAD

**Issue by lynseydesign** [craftcms/fix-fks#4]
ReflectionException: Class craft\fixfks\Command does not exist in /srv/users/serverpilot/apps/c3-staging/releases/1536763236/vendor/yiisoft/yii2/di/Container.php:428
Stack trace:
#0 /srv/users/serverpilot/apps/c3-staging/releases/1536763236/vendor/yiisoft/yii2/di/Container.php(428): ReflectionClass->__construct('craft\\fixfks\\Co...')
#1 /srv/users/serverpilot/apps/c3-staging/releases/1536763236/vendor/yiisoft/yii2/di/Container.php(364): yii\di\Container->getDependencies('craft\\fixfks\\Co...')
#2 /srv/users/serverpilot/apps/c3-staging/releases/1536763236/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('craft\\fixfks\\Co...', Array, Array)
#3 /srv/users/serverpilot/apps/c3-staging/releases/1536763236/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('craft\\fixfks\\Co...', Array, Array)
#4 /srv/users/serverpilot/apps/c3-staging/releases/1536763236/vendor/yiisoft/yii2/db/Connection.php(727): yii\BaseYii::createObject(Array)
#5 /srv/users/serverpilot/apps/c3-staging/releases/1536763236/vendor/craftcms/fix-fks/src/controllers/RestoreController.php(50): yii\db\Connection->createCommand('SET FOREIGN_KEY...')
#6 [internal function]: craft\fixfks\controllers\RestoreController->actionIndex()
#7 /srv/users/serverpilot/apps/c3-staging/releases/1536763236/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#8 /srv/users/serverpilot/apps/c3-staging/releases/1536763236/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#9 /srv/users/serverpilot/apps/c3-staging/releases/1536763236/vendor/craftcms/cms/src/web/Controller.php(103): yii\base\Controller->runAction('', Array)
#10 /srv/users/serverpilot/apps/c3-staging/releases/1536763236/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('', Array)
#11 /srv/users/serverpilot/apps/c3-staging/releases/1536763236/vendor/craftcms/cms/src/web/Application.php(282): yii\base\Module->runAction('fix-fks/restore', Array)
#12 /srv/users/serverpilot/apps/c3-staging/releases/1536763236/vendor/craftcms/cms/src/web/Application.php(541): craft\web\Application->runAction('fix-fks/restore', Array)
#13 /srv/users/serverpilot/apps/c3-staging/releases/1536763236/vendor/craftcms/cms/src/web/Application.php(266): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#14 /srv/users/serverpilot/apps/c3-staging/releases/1536763236/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#15 /srv/users/serverpilot/apps/c3-staging/releases/1536763236/web/index.php(21): yii\base\Application->run()
#16 {main}

**Comment by brandonkelly** [comment]
Sorry about this. We just released v1.0.2.1, which fixes this error.
